# Exercise 1

In this exercise, we will use the iris dataset. Load the "iris.csv" using the appropriate method for this file type (use the new functions from the package).

In [1]:
from si.io.csv_file import read_csv
import numpy as np

iris_ds = read_csv('datasets/iris/iris.csv', features=True, label=True)

print(iris_ds.summary())
print("Shape:", iris_ds.shape())
print("Features:", iris_ds.features)
print("Classes:", iris_ds.get_classes())
print(iris_ds.X)

        sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532
Shape: (150, 4)
Features: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')
Classes: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 

Select the penultimate independent variable. What is the dimension of the resulting array?

In [6]:
pen_variable = iris_ds.X[:, -1]

print('Dim:', len(pen_variable.shape))


Dim: 1


Select the last 10 samples from the iris dataset. What is the mean of the last 10 samples for each independent variable/feature?

In [3]:
last_10 = iris_ds.X[-10:,:]
last_10_mean = last_10.mean(axis=0)

print('Mean:', last_10_mean)


Mean: [6.45 3.03 5.33 2.17]


Select all samples from the dataset with values less than or equal to 6 for all independent variables/features. How many samples do you obtain?


In [4]:
mask = iris_ds.X <= 6
all_true = np.all(mask, axis=1)
f_samples = iris_ds.X[all_true]
n_samples  = f_samples.shape[0]

print("Number of samples ≤ 6:", n_samples )


Number of samples ≤ 6: 89


Select all samples with a class/label different from 'Iris-setosa'. How many samples do you obtain?

In [5]:
mask = iris_ds.y != 'Iris-setosa'
not_iris_setosa = iris_ds.X[mask]
print('All samples with label different from "Iris-setosa":', not_iris_setosa.shape[0])


All samples with label different from "Iris-setosa": 100


# Exercise 2

Examples of how to use the methods from exercise 2

In [1]:
import importlib
import sys
import numpy as np

# O nome completo do seu módulo
MODULE_NAME = 'si.data.dataset'

# Tentar recarregar o módulo se já tiver sido importado
if MODULE_NAME in sys.modules:
    # Importa a referência para o módulo
    module_ref = sys.modules[MODULE_NAME]

    # Força o Python a recarregar o código do disco
    importlib.reload(module_ref)

    print(f"Módulo '{MODULE_NAME}' recarregado com sucesso.")

else:
    pass

# --- Importação da Classe (Deve ser executada SEMPRE após o bloco acima) ---
from si.data.dataset import Dataset

## dropna

In [27]:
X = np.array([[1, 2, 3],
              [4, np.nan, 6],
              [np.nan, 8, 9],
              [10, 11, 12],
              [13,14,np.nan],
              [16,17,18],
              [19,20,21]])

y = np.array([0, 1, 0, 1, 0, 1, np.nan])
dataset = Dataset(X, y,label="Y")

dataset.dropna()
print("X: ", dataset.X)
print("y: ", dataset.y)

X:  [[ 1.  2.  3.]
 [ 9. 10. 11.]
 [15. 16. 17.]]
y:  [0. 1. 1.]


## fillna

In [12]:
X = np.array([[1, 2, 3],
              [4, np.nan, 6],
              [np.nan, 8, 9],
              [10, 11, 12],
              [13,14,np.nan],
              [16,17,18],
              [19,20,21]])

y = np.array([0, 1, 0, 1, 0, 1, 1])
dataset = Dataset(X, y,label="Y")

print('mean:', dataset.get_mean())
dataset.fillna(value = 'mean')
print(dataset.X)

mean: [ 9.66666667 11.         10.5       ]
[[ 1.          2.          3.        ]
 [ 3.         11.          5.        ]
 [ 9.66666667  6.          7.        ]
 [ 9.         10.         11.        ]
 [12.         13.         10.5       ]
 [15.         16.         17.        ]
 [18.         19.         20.        ]]


## remove_by_index

In [15]:
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              ['a', 'a', 'a'],
              [13,14,8],
              [16,17,18],
              [19,20,21]])

y = np.array([0, 1, 0, 1, 0, 1, 1])
dataset = Dataset(X, y,label="Y")

dataset.remove_by_index(3)
print(dataset.X)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']
 ['13' '14' '8']
 ['16' '17' '18']
 ['19' '20' '21']]
