In [7]:
import importlib
import sys
import numpy as np

# O nome completo do seu módulo
MODULE_NAME = 'si.data.dataset'

# Tentar recarregar o módulo se já tiver sido importado
if MODULE_NAME in sys.modules:
    # Importa a referência para o módulo
    module_ref = sys.modules[MODULE_NAME]

    # Força o Python a recarregar o código do disco
    importlib.reload(module_ref)

    print(f"Módulo '{MODULE_NAME}' recarregado com sucesso.")

else:
    pass

# --- Importação da Classe (Deve ser executada SEMPRE após o bloco acima) ---
from si.data.dataset import Dataset


X = np.array([[1, 2, 3],
              [3, np.nan, 5],
              [np.nan, 6, 7],
              [9, 10, 11]])

y = np.array([10, 20, 30, 40])
dataset = Dataset(X, y,label="Y")

print("Features values with missing values:\n",dataset.X)
print("Lables with missing values:",dataset.y)

print("Shape of X without missing values:",dataset.X.shape)
print("Shape of y without missing values:",dataset.y.shape)
print("Features values without missing values:\n",dataset.X)
print("Labels without missing values:",dataset.y)

Módulo 'si.data.dataset' recarregado com sucesso.
Features values with missing values:
 [[ 1.  2.  3.]
 [ 3. nan  5.]
 [nan  6.  7.]
 [ 9. 10. 11.]]
Lables with missing values: [10 20 30 40]
Shape of X with missing values: (4, 3)
Shape of Y with missing values: (4,)
Shape of X without missing values: (4, 3)
Shape of y without missing values: (4,)
Features values without missing values:
 [[ 1.  2.  3.]
 [ 3. nan  5.]
 [nan  6.  7.]
 [ 9. 10. 11.]]
Labels without missing values: [10 20 30 40]


In [8]:
dataset.fillna("median")

array([[ 1.,  2.,  3.],
       [ 3.,  6.,  5.],
       [ 3.,  6.,  7.],
       [ 9., 10., 11.]])

In [9]:
list(zip([1, 2],[1, 0]))

[(1, 1), (2, 0)]